# Visualización básica

En este capítulo presentamos algunas herramientas básicas de visualización en R,
que se pueden aplicar a la creación de gráficos con datos espaciales.

## Datos de ejemplo

Usaremos un *dataset* de ejemplo de un completo libro sobre métodos de regresión,
ya en su segunda edición [@fahrmeir2022]. Los archivos con los datasets de ejemplo de esta
referencia se pueden descargar de su [página web](https://www.uni-goettingen.de/de/551625.html),
así como también los [archivos de código con los modelos](https://www.uni-goettingen.de/de/551585.html)
sobre estos datos, en R.

## El paquete `ggplot2`

### Anatomía de un gráfico con `ggplot2`

El paquete `ggplot2` sigue los principios de la gramática de gráficos (véase el 
[capítulo 4](https://glimmerphoenix.github.io/taller-visualizacion-R/04-grammar.html) de nuestro taller
previo sobre visualización), de forma que nos permite construir un gráfico paso a paso. Para ello
se empieza por utilizar la función `ggplot()`:

1. Indicamos a la función `ggplot()` los datos que vamos a representar. [El argumento
`data = ...`.]{.aside}

2. Indicamos a `ggplot()` *qué* relaciones queremos visualizar. [El argumento `mapping = aes(...)`.]{.aside}

3. Elegimos *cómo* queremos representar gráficamente las relaciones en nuestros datos
que hemos indicado en el paso anterior. [Elegimos una función `geom_...()` que determina
el tipo de gráfico o elemento gráfico.]{.aside}

4. Si es necesario, superponemos más elementos gráficos (objetos geométricos o *geoms*), añadiéndolas a nuestro
gráfico una a una.

5. Incluimos funciones adicionales para ajustar transformar los datos, ajustar o cambiar escalas, 
añadir etiquetas y título, marcas en los ejes, capas adicionales, etc.

Veamos estós datos sobre un esquema para hacernos una idea más clara del aspecto que tendrá nuestro
código.

```r
ggplot(data = <DATOS>,                       # <1>
       mapping = aes(<CONEXIONES>)) +        # <1>
  geom_...(...) +                            # <2>
  stat_...(...) +                            # <3>
  <FUNCIONES DE ESCALA Y GUÍAS> +            # <4>
  <SISTEMAS COORDENADOS> +                   # <5>
  <FACETAS> +                                # <6>
  <TEMA>                                     # <7>
```
1. Indicamos qué datos vamos a utilizar y como conectamos esos datos (mapeo) con los elementos estéticos. Esta parte es **obligatoria**.
2. Añadimos uno o varios objetos geométricos para representar los datos.
3. Transformamos los datos (funciones `stat_...()`), normalmente resumiéndolos de algún modo. 
4. Ajustamos el mapeo de los datos a los elementos estéticos, modificando la escala de representación o añadiendo 
elementos de guía para intepretar el gráfico (marcas en ejes, leyenda, etc.).
5. Configuramos el sistema coordenado de representación (por defecto se usan coordenadas cartesianas): intercambio de ejes X e Y
(función `coord_flip()`), uso de coordenadas polares (`coord_polar()`), etc.
6. Decidimos si queremos desglosar el gráfico en varios paneles (*facets*) para presentar simultáneamente varios subgráficos
(como hemos visto, útil para comparar entre grupos, evolución temporal y en otros casos).
7. Por último, podemos elegir un tema preconfigurado que adapta el aspecto de muchos de los elementos del gráfico para conseguir
un resultado final más armonizado.

::: {.callout-note collapse="true"}
## Información adicional sobre `ggplot2`

Si necesitas más información sobre la utilización del paquete `ggplot2` te recomendamos que consultes
las siguientes referencias:

- [Capítulo 5](https://www.uni-goettingen.de/de/551625.html) de nuestro curso previo
    *Visualización de Datos con R*, para este mismo programa de doctorado.
- Manual oficial de `ggplot2`: <https://ggplot2-book.org> (3ª ed., en progreso).
:::

### Ejemplo básico de representación

```{r}
#| label: fig-beech-2ch
#| fig-cap: "Visualización utilizando dos canales y facetas."
#| fig-height: 12
#| fig-width: 15
#| column: page-right
library(ggplot2)
library(Hmisc)
library(readr)

# Lectura de datos; consulta la explicación en el capítulo 7
beech <- read_table("data/beech.raw",
  col_types = cols(id = col_integer(), year = col_integer(), age = col_integer(),
                   canopyd = col_integer(), gradient = col_integer(),
                   alt = col_integer(), depth = col_integer(), ph = col_double(),
                   watermoisture = col_factor(levels = c("1", "2", "3")),
                   alkali = col_factor(levels = c("1","2", "3", "4")),
                   humus = col_factor(levels = c("0", "1", "2", "3", "4",
                                                 "5", "6", "7", "8", "9")),
                   type = col_factor(levels = c("0","1")),
                   fert = col_factor(levels = c("0","1"))
                   ))

beech_years <- beech |>
               dplyr::filter(year == 2004)

p_beech <- ggplot(data = beech_years,
                  aes(x = x, y = y,
                      color = defol, size = age)) +
           geom_point(alpha = 0.6) +
           labs(title = "Bosque the Rothenbuch (Spessart)",
                subtitle = "Axel Göttlein (Tech. Univ., Munich). Año: 2004.") +
           theme(
            legend.text = element_text(size = 12),
            legend.title = element_text(size = 14),
            strip.text = element_text(size = 12),
            axis.text = element_text(size = 12),
            axis.title = element_text(size = 14),
           )
p_beech
```

### Mapas estáticos


