# Paquetes R y atribuciones

## Paquetes R {#sec-pkg-requirements}

Para ejecutar los ejemplos incluidos en este taller, se necesita tener instalado
R y una IDE de desarrollo para este lenguaje, como por ejemplo RStudio o Microsoft
VS Code.

Además, es necesario instalar los paquete descritos en la @tbl-R-packages.

| Paquete        | Descripción                                                    |
|:---------------|:---------------------------------------------------------------|
| `ggplot2`      | Paquete principal de visualización de datos en el Tidyverse      |
| `tidyverse`    | Metapaquete que instala las herramientas principales del Tidyverse      |
| `agridat`      | Conjunto de datos sobre experimentos  deagricultura, incluyendo cultivos de campo, cultivos arbóreos o estudios con animales, entre otros      |
| `Hmisc`        | Funciones de utilidad desarrolladas por Frank E. Harrell      |
| `ggthemes`     | Temas adicionales para personalizar gráficos con `ggplot2`       |
| `sf`           | Soporte para manipulación y representación de objetos codificados con el estándar *simple features*      |
| `terra`        | Soporte para manipulación y representación de objetos de tipo *raster*      |
| `mapview`      | Creación de gráficos espaciales intereactivos en R      |
| `mapSpain`     | Facilita la creación de mapas a diferentes niveles administrativos de España    |
| `climaemet`    | Acceso a datos de la AEMET desde R     |
| `airqualityES` | Datos sobre calidad del aire en España (periodio de 18 años)     |

: Listado de paquetes R utilizados en los ejemplos de este taller. {#tbl-R-packages .striped .hover}


## Atribución de imágenes e iconos

Todas las imágenes utilizadas de fuentes externas reciben atribución junto a su aparición
en los contenidos de este taller.